### ISSUE TITLE
SSH Bad configuration option: auto_unmount

### ISSUE THREAD

**Issue by gkzsolt** [efficiosoft/btrfs-backup#23] opened 2018-05-13 11:17 UTC
Hi,
I am trying to backup a snapshot to a remote server, but to this command:
`btrfs-backup /tank ssh://my-pc/test-backups`
I got the following:
`11:45:04  [INFO ]  --[ Started at Sun May 13 11:45:04 2018 ]---------
11:45:04  [INFO ]  Preparing endpoint /tank/snapshot ...
11:45:04  [INFO ]  Preparing endpoint (SSH) my-pc/test-backups ...
command-line: line 0: Bad configuration option: auto_unmount
11:45:04  [ERROR]  Error on command: ['ssh', '-o', 'auto_unmount', '-o', 'reconnect', '-o', 'cache=no', 'my-pc', 'mkdir', '-p', '/test-backups']`
(I'm sorry, I don't know how to set preformatted line-breaks in comments).
What is this `auto_unmount` option to ssh?

**Comment by efficiosoft** [comment] 2018-05-13 11:34
This is a duplicate of https://github.com/efficiosoft/btrfs-backup/issues/19. You should always try to use the latest available version before opening an issue.

Best regards
Robert

**Closed** 2018-05-13 11:34 UTC
